import { describe, it, expect, vi } from 'vitest'
import type { SupabaseClient } from '@supabase/supabase-js'
import {
  fetchRecentAutoGenerated,
  formatReport,
  type AutoGeneratedIngredient,
} from './auto-generated-report'

const FROM = new Date('2026-08-04T00:00:00Z')
const TO = new Date('2026-08-11T00:00:00Z')

function item(
  name: string,
  category: string,
  createdAt = '2026-08-05T00:00:00Z'
): AutoGeneratedIngredient {
  return { name, category, created_at: createdAt }
}

/**
 * select().eq().gte().order() のチェーンを記録する最小のモッククライアント。
 * 各段に渡された引数を検証できるよう spy を返す。
 */
function createMockClient(response: { data: unknown; error: unknown }) {
  const order = vi.fn(async () => response)
  const gte = vi.fn(() => ({ order }))
  const eq = vi.fn(() => ({ gte }))
  const select = vi.fn(() => ({ eq }))
  const client = { from: () => ({ select }) } as unknown as SupabaseClient
  return { client, select, eq, gte, order }
}

describe('formatReport', () => {
  it('カテゴリ別にグルーピングし、その他を最後に置く', () => {
    const text = formatReport(
      [
        item('鶏ガラスープの素', 'その他'),
        item('エシャレット', '野菜'),
        item('厚揚げ', '豆腐・大豆製品'),
        item('芽キャベツ', '野菜'),
      ],
      { from: FROM, to: TO }
    )

    const categoryOrder = [...text.matchAll(/【(.+?)】/g)].map((m) => m[1])
    expect(categoryOrder).toEqual(['野菜', '豆腐・大豆製品', 'その他'])
    // 同カテゴリの食材は1つの見出しにまとまる
    expect(text).toContain('【野菜】\n・エシャレット\n・芽キャベツ')
  })

  it('期間を JST の M/D で表示し、件数を出す', () => {
    const text = formatReport([item('厚揚げ', '豆腐・大豆製品')], { from: FROM, to: TO })

    // UTC 8/4 00:00 → JST 8/4 09:00、UTC 8/11 00:00 → JST 8/11 09:00
    expect(text).toContain('🔍 自動追加食材レポート (8/4〜8/11)')
    expect(text).toContain('今週 1 件が自動追加されました。')
  })

  it('0 件でも本文を返す（通知が来ない＝ジョブ故障と判別するため）', () => {
    const text = formatReport([], { from: FROM, to: TO })

    expect(text).toContain('今週の自動追加はありませんでした（0 件）。')
    // 0 件のときは修正 SQL を出さない
    expect(text).not.toContain('UPDATE ingredients')
  })

  it('maxItems を超えたら打ち切り、省略件数と総件数を明示する', () => {
    const items = Array.from({ length: 5 }, (_, i) => item(`食材${i}`, '野菜'))

    const text = formatReport(items, { from: FROM, to: TO, maxItems: 2 })

    expect(text).toContain('・食材0')
    expect(text).toContain('・食材1')
    expect(text).not.toContain('・食材2')
    expect(text).toContain('…他 3 件（全 5 件）は省略しました。')
    // 見出しの件数は打ち切り後ではなく実際の総件数
    expect(text).toContain('今週 5 件が自動追加されました。')
  })

  it('修正 SQL の雛形を含む', () => {
    const text = formatReport([item('厚揚げ', 'その他')], { from: FROM, to: TO })

    expect(text).toContain("UPDATE ingredients SET category='X' WHERE name='Y';")
    expect(text).toContain("UPDATE ingredients SET needs_review=true WHERE name='Y';")
  })
})

describe('fetchRecentAutoGenerated', () => {
  it('auto_generated = true かつ直近 days 日で引く', async () => {
    const rows = [item('厚揚げ', '豆腐・大豆製品')]
    const { client, select, eq, gte, order } = createMockClient({ data: rows, error: null })

    const result = await fetchRecentAutoGenerated(client, 7, new Date('2026-08-11T00:00:00Z'))

    expect(result).toEqual(rows)
    expect(select).toHaveBeenCalledWith('name, category, created_at')
    expect(eq).toHaveBeenCalledWith('auto_generated', true)
    expect(gte).toHaveBeenCalledWith('created_at', '2026-08-04T00:00:00.000Z')
    expect(order).toHaveBeenCalledWith('created_at', { ascending: true })
  })

  it('DB エラーは throw する（空レポートを送って正常に見せない）', async () => {
    const { client } = createMockClient({
      data: null,
      error: { code: '42501', message: 'permission denied' },
    })

    await expect(fetchRecentAutoGenerated(client, 7)).rejects.toThrow('permission denied')
  })
})
