/**
 * 自動追加食材の事後監査レポート
 *
 * auto-alias が自動追加した食材（auto_generated = TRUE）を週次で洗い出し、
 * 管理者への LINE 通知本文を組み立てる。
 *
 * #148 で自動追加食材を即時有効化（needs_review = false）したため、
 * 妥当性の確認は事後監査に委ねている（Issue #150）。
 * #144 のカテゴリ語検索により、カテゴリ誤りは検索品質に直結するため
 * 名前だけでなくカテゴリも必ず載せる。
 */

import { SupabaseClient } from '@supabase/supabase-js'

/** 1通に載せる最大件数（LINE テキストは 5000 字上限） */
const DEFAULT_MAX_ITEMS = 30

/** 最後に回すカテゴリ（分類できなかったものの吹き溜まりなので目立たせない） */
const FALLBACK_CATEGORY = 'その他'

export interface AutoGeneratedIngredient {
  name: string
  category: string
  created_at: string
}

export interface FormatReportOptions {
  from: Date
  to: Date
  maxItems?: number
}

/**
 * 直近 days 日以内に自動追加された食材を created_at 昇順で取得する
 *
 * 部分インデックス idx_ingredients_auto_generated が効く条件で引く。
 */
export async function fetchRecentAutoGenerated(
  supabase: SupabaseClient,
  days: number,
  now: Date = new Date()
): Promise<AutoGeneratedIngredient[]> {
  const since = new Date(now.getTime() - days * 24 * 60 * 60 * 1000)

  const { data, error } = await supabase
    .from('ingredients')
    .select('name, category, created_at')
    .eq('auto_generated', true)
    .gte('created_at', since.toISOString())
    .order('created_at', { ascending: true })

  if (error) {
    console.error('[fetchRecentAutoGenerated] Error:', error)
    throw new Error(`Failed to fetch auto-generated ingredients: ${error.message}`)
  }

  return (data ?? []) as AutoGeneratedIngredient[]
}

/** M/D 形式（JST）。Edge Function は UTC で動くため明示的に変換する */
function formatDateJst(date: Date): string {
  const jst = new Date(date.getTime() + 9 * 60 * 60 * 1000)
  return `${jst.getUTCMonth() + 1}/${jst.getUTCDate()}`
}

/**
 * カテゴリ別にグルーピングする
 *
 * カテゴリの一覧はここでは持たない（alias-db.ts 等に既に散在しており、
 * コピーを増やすと増減時のズレ元になる）。順序は出現順で、
 * 「その他」だけ末尾に回す。
 */
function groupByCategory(
  items: AutoGeneratedIngredient[]
): Array<{ category: string; names: string[] }> {
  const groups = new Map<string, string[]>()

  for (const item of items) {
    const names = groups.get(item.category)
    if (names) {
      names.push(item.name)
    } else {
      groups.set(item.category, [item.name])
    }
  }

  const entries = [...groups.entries()].map(([category, names]) => ({ category, names }))
  return [
    ...entries.filter((e) => e.category !== FALLBACK_CATEGORY),
    ...entries.filter((e) => e.category === FALLBACK_CATEGORY),
  ]
}

/** 修正手順（そのまま SQL Editor に貼れる雛形） */
function footer(): string {
  return [
    '▼カテゴリ修正',
    "UPDATE ingredients SET category='X' WHERE name='Y';",
    '▼誤登録を非表示',
    "UPDATE ingredients SET needs_review=true WHERE name='Y';",
  ].join('\n')
}

/**
 * 通知本文を組み立てる
 *
 * 0 件でも本文を返す。通知が届かないこと自体を「ジョブ故障」の合図にするため、
 * 静かに送信をやめる選択はしない（Issue #150）。
 */
export function formatReport(
  items: AutoGeneratedIngredient[],
  options: FormatReportOptions
): string {
  const range = `${formatDateJst(options.from)}〜${formatDateJst(options.to)}`
  const header = `🔍 自動追加食材レポート (${range})`

  if (items.length === 0) {
    return `${header}\n今週の自動追加はありませんでした（0 件）。`
  }

  const maxItems = options.maxItems ?? DEFAULT_MAX_ITEMS
  const shown = items.slice(0, maxItems)
  const omitted = items.length - shown.length

  const body = groupByCategory(shown)
    .map(({ category, names }) => [`【${category}】`, ...names.map((n) => `・${n}`)].join('\n'))
    .join('\n\n')

  const sections = [`${header}\n今週 ${items.length} 件が自動追加されました。`, body]

  if (omitted > 0) {
    sections.push(`…他 ${omitted} 件（全 ${items.length} 件）は省略しました。`)
  }

  sections.push(footer())

  return sections.join('\n\n')
}
