/**
 * 自動追加食材の事後監査通知 Edge Function
 *
 * pg_cron から週1回呼び出され、直近7日間に auto-alias が自動追加した食材を
 * 管理者の LINE に push する。
 *
 * #148 で自動追加食材を即時有効化したため承認 UI は無い。カテゴリ誤りは
 * #144 のカテゴリ語検索を静かに劣化させるので、名前とカテゴリを目視できる
 * 経路をここで担保する（Issue #150）。
 *
 * 1クエリ + 1 push で完結するため auto-alias のような非同期パターンは使わない。
 *
 * 環境変数:
 *   - SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY: 自動設定
 *   - LINE_CHANNEL_ACCESS_TOKEN: 手動で Secrets に設定
 *   - LINE_ADMIN_USER_ID: 通知先（管理者の LINE user id）
 */

import { createClient } from 'npm:@supabase/supabase-js@2'

// NOTE: auto-generated-report.ts はビルド時に自動生成されます
// ソース: src/lib/batch/auto-generated-report.ts
// 生成コマンド: npx tsx scripts/build-edge-functions.ts
import { fetchRecentAutoGenerated, formatReport } from './auto-generated-report.ts'

const REPORT_DAYS = 7

const LINE_PUSH_ENDPOINT = 'https://api.line.me/v2/bot/message/push'

/** LINE Messaging API にテキストを push する（Deno なので SDK は使わず fetch 直叩き） */
async function pushText(token: string, to: string, text: string): Promise<void> {
  const res = await fetch(LINE_PUSH_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({ to, messages: [{ type: 'text', text }] }),
  })

  if (!res.ok) {
    // 本文まで残さないと 400（invalid user id 等）の切り分けができない
    throw new Error(`LINE push failed: ${res.status} ${await res.text()}`)
  }
}

function errorResponse(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })
}

Deno.serve(async () => {
  const supabaseUrl = Deno.env.get('SUPABASE_URL')
  const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
  const lineToken = Deno.env.get('LINE_CHANNEL_ACCESS_TOKEN')
  const adminUserId = Deno.env.get('LINE_ADMIN_USER_ID')

  if (!supabaseUrl || !supabaseKey) {
    return errorResponse('Missing Supabase credentials', 500)
  }

  if (!lineToken || !adminUserId) {
    return errorResponse('Missing LINE_CHANNEL_ACCESS_TOKEN or LINE_ADMIN_USER_ID', 500)
  }

  try {
    const supabase = createClient(supabaseUrl, supabaseKey)
    const now = new Date()

    const items = await fetchRecentAutoGenerated(supabase, REPORT_DAYS, now)
    const text = formatReport(items, {
      from: new Date(now.getTime() - REPORT_DAYS * 24 * 60 * 60 * 1000),
      to: now,
    })

    await pushText(lineToken, adminUserId, text)

    console.log(`[audit-auto-generated] Notified ${items.length} auto-generated ingredients`)

    return new Response(JSON.stringify({ status: 'ok', count: items.length }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    })
  } catch (err) {
    console.error('[audit-auto-generated] Error:', err)
    return errorResponse(err instanceof Error ? err.message : 'Unknown error', 500)
  }
})
