/**
 * 自動追加食材の事後監査レポート確認スクリプト
 *
 * Edge Function `audit-auto-generated` が送る本文をローカルで組み立てて確認する。
 * Issue #150
 *
 * 使い方:
 *   # 本文を標準出力するだけ（デフォルト・送信しない）
 *   npx tsx scripts/audit-auto-generated.ts
 *
 *   # 期間を変える（ローカル DB に自動追加食材が少ない場合に広げる）
 *   npx tsx scripts/audit-auto-generated.ts --days=3650
 *
 *   # 実際に管理者へ LINE 送信する
 *   npx tsx scripts/audit-auto-generated.ts --push
 *
 *   # ステージング環境
 *   npx tsx scripts/audit-auto-generated.ts --env=staging
 *
 * 環境変数ファイル:
 *   --env=local    → .env.local（デフォルト）
 *   --env=staging  → .env.staging
 *
 * --push には LINE_CHANNEL_ACCESS_TOKEN と LINE_ADMIN_USER_ID が必要。
 */

import { readFileSync, existsSync } from 'fs'
import { createClient } from '@supabase/supabase-js'

const LINE_PUSH_ENDPOINT = 'https://api.line.me/v2/bot/message/push'

function parseArgs() {
  const options = { env: 'local', days: 7, push: false }

  for (const arg of process.argv.slice(2)) {
    if (arg.startsWith('--env=')) {
      options.env = arg.split('=')[1]
    } else if (arg.startsWith('--days=')) {
      options.days = parseInt(arg.split('=')[1], 10)
    } else if (arg === '--push') {
      options.push = true
    }
  }

  return options
}

function loadEnvFile(envName: string): void {
  const envFilePath = `.env.${envName}`

  if (!existsSync(envFilePath)) {
    console.error(`エラー: ${envFilePath} が見つかりません`)
    process.exit(1)
  }

  console.log(`環境: ${envName} (${envFilePath})\n`)

  const envFile = readFileSync(envFilePath, 'utf-8')
  for (const line of envFile.split('\n')) {
    const match = line.match(/^([^=]+)=(.*)$/)
    if (match) {
      process.env[match[1]] = match[2]
    }
  }
}

async function pushText(token: string, to: string, text: string): Promise<void> {
  const res = await fetch(LINE_PUSH_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
    body: JSON.stringify({ to, messages: [{ type: 'text', text }] }),
  })

  if (!res.ok) {
    throw new Error(`LINE push failed: ${res.status} ${await res.text()}`)
  }
}

async function main() {
  const options = parseArgs()
  loadEnvFile(options.env)

  // 環境変数読み込み後に動的インポート
  const { fetchRecentAutoGenerated, formatReport } = await import(
    '../src/lib/batch/auto-generated-report'
  )

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SECRET_KEY!
  )

  const now = new Date()
  const items = await fetchRecentAutoGenerated(supabase, options.days, now)
  const text = formatReport(items, {
    from: new Date(now.getTime() - options.days * 24 * 60 * 60 * 1000),
    to: now,
  })

  console.log('=== 通知本文 ===')
  console.log(text)
  console.log(`\n=== 対象件数: ${items.length} 件（直近 ${options.days} 日） ===`)

  if (!options.push) {
    console.log('\n※ 送信していません。実際に送るには --push を付けてください')
    return
  }

  const token = process.env.LINE_CHANNEL_ACCESS_TOKEN
  const adminUserId = process.env.LINE_ADMIN_USER_ID

  if (!token || !adminUserId) {
    console.error('エラー: LINE_CHANNEL_ACCESS_TOKEN と LINE_ADMIN_USER_ID が必要です')
    process.exit(1)
  }

  await pushText(token, adminUserId, text)
  console.log('\n✅ LINE に送信しました')
}

main().catch((err) => {
  console.error('エラー:', err)
  process.exit(1)
})
